### ISSUE TITLE
Does map-macro abuse the inconsistency in the standard?

### ISSUE THREAD

**Issue by Hirrolot** [swansontec/map-macro#10]
Apparently, there's a known inconsistency in the standard: http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#268 (it's actually C++, but the same paragraph is presented in the C [standard] too).

So consider this code:

```c
#define MAP_OUT
#define A(x) x B MAP_OUT (x)
#define B(x) x A MAP_OUT (x)

#define EXPAND(...) __VA_ARGS__

B(blah)
```

`B(blah)`, after some consecutive rescans, expands to `x B MAP_OUT (x)`, which contains the same macro name `B` (yes, in different contexts, but it seems irrelevant according to the [standard]):

> ... These nonreplaced macro name preprocessing tokens are no longer available for further replacement even if they are later (re)examined in contexts in which that macro name preprocessing token would otherwise have been replaced.

Putting things together, does map-macro exploit the inconsistency (presented in the first link I gave) that it's not clear that `B` in `x B MAP_OUT (x)` occurs in nested expansions of `B(blah)` or does not, which affects whether it's blueprinted or not?

[standard]: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

**Comment by Hirrolot** [comment]
It seems that it does **not**, because a single scan of `x A MAP_OUT (x)` does not result in `B`, and hence it's not blueprinted. The quote about different contexts concerns about already blueprinted macros.

**Comment by Hirrolot** [comment]
Though I'm not completely sure about this. Does `A(blah)`, produced from `B(blah)`, belongs to a set of macros to expand, according to the standard?

**Comment by swansontec** [comment]
After carefully re-reading section 6.10.3.4 in the C standard you linked, I think we may be OK.

This non-replacement logic only applies to the "name of the macro being replaced". Since expanding `A` doesn't produce the token `A` anywhere in the output, the whole section is irrelevant.

The problem you linked would be relevant if `A` produced the token `A` again after additional macro expansions. In the committee's example, the macro `NIL` produces `G_1`, which then produces `NIL` again. That second `NIL` shouldn't be expanded, since it came from a macro called `NIL`, but maybe it should be expanded, because `NIL` isn't currently in the macro call stack? That is the choice the committee is worried about. We don't have this situation, because `A` just doesn't produce any token called `A`, no matter how far down you go. That means nothing ever ends up on the banned tokens list.

**Comment by Hirrolot** [comment]
Yes, you're right. Also my SO question: https://stackoverflow.com/questions/64010028/does-recursion-in-the-c-preprocessor-abuse-an-inconsistency-in-the-standard.
